name: Auto Package

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
  
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: fix file
        run: chmod 0755 -R clash_for_windows/DEBIAN
      
      - name: Run Script
        env:
          GITHUB_TOKEN: ${{ secrets.CLASH_TOKEN }}
        run: php build_publish.php
